accounts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts import views


urlpatterns = [
    url(r'^$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
]

solomon/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts import urls as accounts_urls
# from dashboard import urls as dashboard_urls
# from dashboard import views as dashboard_views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include(accounts_urls, namespace='accounts')),
    
    # url(r'^$', dashboard_views.dashboard, name='home'),
    # url(r'^add/item/', dashboard_views.add_item, name='add_item'),
    # url(r'^add/arrival/', dashboard_views.add_arrival, name='add_arrival'),
    # url(r'^add/sales/', dashboard_views.add_sales, name='add_sales'),
    # url(r'^transfer/', dashboard_views.transfer_item, name='transfer_item'),

    # url(r'^reports/items/', dashboard_views.item_reports, name='item_reports'),
    # url(r'^reports/arrivals/', dashboard_views.arrival_reports, name='arrival_reports'),
    # url(r'^reports/sales/', dashboard_views.sales_reports, name='sales_reports'),
    # url(r'^reports/transfers/', dashboard_views.transfer_reports, name='transfer_reports'),

    # url(r'^notifications/', dashboard_views.notifications, name='notifications'),
]

accounts/models.py
from django.db import models

# Create your models here.

inventory/models.py
from django.db import models


class Item(models.Model):
	store_code = models.CharField(max_length=200, null=True)	# Store Code
	supplier_code = models.CharField(max_length=200, null=True)	# Supplier Code
	status = models.CharField(max_length=50, null=True, default="INACTIVE") 		# Active or Inactive
	unit_cost = models.IntegerField(default=0)

	created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

	category = models.ForeignKey("Category", db_index=True, null=True)
	brand = models.ForeignKey("Brand", db_index=True, null=True)
	item_model = models.ForeignKey("ItemModel", db_index=True, null=True)
	supplier = models.ForeignKey("Supplier", db_index=True, null=True)

	class Meta:
		ordering = ('created',)

class Supplier(models.Model):
	""" Suppliers can be also be paying users """
	name = models.CharField(max_length=200, null=True)
	address = models.CharField(max_length=200, null=True)
	phone = models.CharField(max_length=200, null=True)

	# owner = models.ForeignKey("accounts.User")

class Category(models.Model):
	""" Categories describe an Item """
	description = models.CharField(max_length=100, null=True)

class Brand(models.Model):
	""" Brands describe an Item """
	description = models.CharField(max_length=100, null=True)

class ItemModel(models.Model):
	""" Models describe the model of a particular Item """
	description = models.CharField(max_length=100, null=True)





"""
from django.db import models

class Item(models.Model):
	category = models.CharField(max_length=200, null=True)
	itemType = models.CharField(max_length=200, null=True)
	
	itemCode = models.CharField(max_length=200, null=True)
	supplierCode = models.CharField(max_length=200, null=True)
	minimumRequired = models.IntegerField(default=0)
	store_quantity = models.IntegerField(default=0)
	warehouse_quantity = models.IntegerField(default=0)
	unit_cost = models.BigIntegerField(default=0)
	supplier = models.ForeignKey("dashboard.Supplier", db_index=True, null=True)

	def __unicode__(self):
		return "%s | %s | %s | %s" % (self.category, self.itemType, self.itemModel, self.brand)

	@staticmethod
	def get_inventory_balance():
		total_item_cost = 0
		item_list = Item.objects.all()
		for item in item_list: 
			total_item_cost += item.unit_cost * (item.store_quantity + item.warehouse_quantity) 
		return total_item_cost

class Arrival(models.Model):
	item = models.ForeignKey("dashboard.Item", db_index=True, null=True, blank=True)
	date = models.DateField(auto_now=True, null=True)
	tracking_number = models.CharField(max_length=200, null=True)
	delivery_receipt = models.CharField(max_length=200, null=True)
	quantity = models.IntegerField(default=0)

class Sale(models.Model):
	item = models.ForeignKey("dashboard.Item", db_index=True, null=True, blank=True)
	quantity = models.IntegerField(default=0)
	date = models.DateField(auto_now=True, null=True)

	@property
	def total_cost(self):
		return self.quantity * self.item.unit_cost

	@staticmethod
	def grand_total():
		grand_total = 0
		all_sales = Sale.objects.all()
		for sale in all_sales: 
			grand_total += sale.total_cost
		return grand_total

class Transfer(models.Model):
	item = models.ForeignKey("dashboard.Item", db_index=True, null=True, blank=True)
	quantity = models.IntegerField(default=0)
	date = models.DateField(auto_now=True, null=True)
	location_to = models.CharField(max_length=200, null=True)
	location_from = models.CharField(max_length=200, null=True)

class Supplier(models.Model):
	description = models.CharField(max_length=200, null=True)
	address = models.CharField(max_length=200, null=True)
	phone = models.CharField(max_length=200, null=True)

	def __unicode__(self):
		return self.description

"""

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render
from django.http import HttpResponse


def login(request):
	return HttpResponse({"LOGIN"})

inventory/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Item, Supplier, Category, Brand, ItemModel

def add_item(request):
	if request.method == 'POST':
		# Save the rest of the fields from the POST trigger
		store_code = request.POST.get('store_code')
		supplier_code = request.POST.get('supplier_code')
		unit_cost = request.POST.get('unit_cost')

		# Todo : Move to models (Fat Models, Stupid Views)
		new_item = Item(store_code=store_code, supplier_code=supplier_code, unit_cost=unit_cost)
		new_item.status = "ACTIVE"
		new_item.save()
	return HttpResponse({""})

def add_supplier(request):
	if request.method == 'POST':
		name = request.POST.get('name')
		address = request.POST.get('address')
		phone = request.POST.get('phone')

		new_supplier = Supplier(name=name, address=address, phone=phone)
		new_supplier.save()
	return HttpResponse({""})

def add_category(request):
	if request.method == 'POST':
		description = request.POST.get('description')
		new_category = Category(description=description)
		new_category.save()
	return HttpResponse({""})

def add_brand(request):
	if request.method == 'POST':
		description = request.POST.get('description')
		new_brand = Brand(description=description)
	return HttpResponse({""})

def add_item_model(request):
	if request.method == 'POST':
		description = request.POST.get('description')
		new_item_model = ItemModel(description=description)
		new_item_model.save()
	return HttpResponse({""})	
















"""def dashboard(request):
	return render(request, 'dashboard/home.html', {})

def add_item(request):
	return render(request, 'dashboard/add_item.html', {})

def add_arrival(request):
	return render(request, 'dashboard/add_arrival.html', {})

def add_sales(request):
	return render(request, 'dashboard/add_sales.html', {})

def transfer_item(request):
	return render(request, 'dashboard/transfer_item.html', {})

def notifications(request):
	return render(request, 'dashboard/notifications.html', {})

def item_reports (request):
	item_list = Item.objects.all()
	item_list_length = len(item_list)
	inventory_balance = Item.get_inventory_balance()
	print inventory_balance

	return render(request, 'reports/item_reports.html', {
		'items': item_list,
		'length' : item_list_length,
		'inventory_value': inventory_balance,
	})

def arrival_reports (request):
	return render(request, 'reports/arrival_reports.html', {})

def sales_reports (request):
	sales_list = Sale.objects.all()
	sales_list_length = len(sales_list)
	return render(request, 'reports/sales_reports.html', {
		'date_period': 'October',
		'sales': sales_list, 
		'sales_length' : sales_list_length,
		'sales_total'  : Sale.grand_total()
	})

def transfer_reports (request):
	return render(request, 'reports/transfer_reports.html', {})"""

accounts/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Inventory Management System, Logistics & Supply Chain Management</title>
</head>
<body>
	<div>
      {{ user }}
      {% if user.is_anonymous %}
      <a href="{% url 'accounts:login' %}">login</a>
      {% else %}
      <a href="{% url 'accounts:logout' %}">logout</a>
      {% endif %}
    </div>
	{% block content %}{% endblock %}
</body>
</html>

inventory/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>POS + Inventory System</title>

	<!-- Local Scripts & Styles -->
	<!--<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
	<script type="text/javascript" src="/static/js/jquery.js"></script>
	<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>-->

	<!-- Data Tables + Bootstrap + Jquery -->
	<!-- http://datatables.net/ -->
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">
	<link rel="stylesheet" type="text/css" href="/static/vendor/datatables/datatables.min.css">
	<script type="text/javascript" src="/static/vendor/datatables/datatables.min.js"></script>
	<script type="text/javascript" src="/static/js/scripts.js"></script>

</head>
<body>
	<div class="section-navbar">
		<nav class="navbar navbar-default">
		  	<div class="container">
			    <div class="navbar-header">
			    	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				        <span class="sr-only">Toggle navigation</span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
			      	</button>
			      	<a class="navbar-brand" href="{% url 'home' %}">Inventory</a>
			    </div>
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      	<ul class="nav navbar-nav">
			      		<li class="dropdown">
				          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Transactions <span class="caret"></span></a>
				          <ul class="dropdown-menu">
				            <li><a href="{% url 'add_item' %}">Add Inventory Item</a></li>
				            <li><a href="{% url 'add_arrival' %}">Add Arrival</a></li>
				            <li><a href="{% url 'add_sales' %}">Add Sales</a></li>
				            <li role="separator" class="divider"></li>
				            <li><a href="{% url 'transfer_item' %}">Transfer Items</a></li>
				          </ul>
				        </li>
				        <li class="dropdown">
				          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports <span class="caret"></span></a>
				          <ul class="dropdown-menu">
				            <li><a href="{% url 'item_reports' %}">Inventory</a></li>
				            <li><a href="{% url 'arrival_reports' %}">Arrivals</a></li>
				            <li><a href="{% url 'sales_reports' %}">Sales</a></li>
				            <li><a href="{% url 'transfer_reports' %}">Transfers</a></li>
				          </ul>
				        </li>
			      	</ul>
			      	<ul class="nav navbar-nav navbar-right">
			        	<li><a href="{% url 'notifications' %}">Notifications</a></li>
			        	<li class="dropdown">
				          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
				          <ul class="dropdown-menu">
				            <li><a href="">Profile</a></li>
				            <li><a href="#">Logout</a></li>
				          </ul>
				        </li>
			      	</ul>
			    </div><!-- /.navbar-collapse -->
		  	</div><!-- /.container-fluid -->
		</nav>
	</div>
	<div class="section-content">
		{% block content %}{% endblock %}
	</div>
	<div class="section-footer"></div>
</body>
</html>

inventory/templates/inventory/add_arrival.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<div class="container">
		<div class="newsfeed">
			<form class="form">
				<label>Date</label>
				<input type="text" class="form-control">
			</form>
		</div>
	</div>
	
{% endblock %}

inventory/templates/inventory/add_item.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<div class="container">
		<h1>Add Item</h1>
		<div class="row">
			<div class="col-md-8">
				<form class="form">
					<div class="form-group">
						<label for="category">Category</label>
						<input name="category" class="form-control" type="text">
					</div>
					<div class="form-group">
						<label for="brand">Brand</label>
						<input name="brand" class="form-control" type="text">
					</div>
					<div class="form-group">
						<label for="model">Model</label>
						<input name="model" class="form-control" type="text">
					</div>
					<div class="form-group">
						<label for="supplier">Supplier</label>
						<input name="supplier" class="form-control" type="text">
					</div>
					<div class="form-group">
						<input name="submit" class="form-control" type="submit" value="Submit">
					</div>
				</form>
			</div>
		</div>
	</div>
	
{% endblock %}

inventory/templates/inventory/add_sales.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<div class="container">
		<div class="newsfeed">
			<h1>Add Sales</h1>
		</div>
	</div>
	
{% endblock %}

inventory/templates/inventory/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<div class="container">
		<div class="newsfeed">
			<h1>News Feed</h1>
		</div>
	</div>
	
{% endblock %}

inventory/templates/inventory/notifications.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<div class="container">
		<div class="newsfeed">
			<h1>Notifications</h1>
		</div>
	</div>
	
{% endblock %}

inventory/templates/inventory/reports.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<div class="container">
		<div class="newsfeed">
			<h1>Reports</h1>
		</div>
	</div>
	
{% endblock %}

inventory/templates/inventory/transfer_item.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<div class="container">
		<div class="newsfeed">
			<h1>Transfer Item</h1>
		</div>
	</div>
	
{% endblock %}

inventory/templates/reports/item_reports.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Inventory Reports</h1>
				<p>This page will output all the items in inventory.</p>
				<hr>
			</div>
		</div><br>
		<div class="row">
			<div class="col-md-6">
				<table class="table table-striped table-bordered">
					<thead>
						<tr>
							<th colspan="2">Results Summary</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Total items in inventory</td>
							<td>{{ length }}</td>
						</tr>
						<tr>
							<td>Inventory Value</td>
							<td>P {{ inventory_value }} </td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<!-- TODO: AVOID DATA BINDING IN DOM -->
				<table id="item_reports" class="table table-hover table-bordered table-condensed table-responsive">
					<thead>
						<tr>
							<th>Item ID</th>
							<th>Item Code</th>
							<th>Supplier Code</th>
							<th>Category</th>
							<th>Type</th>
							<th>Brand</th>
							<th>Model</th>
							<th>Supplier</th>
							<th>Minimum Required in Inventory</th>
							<th>Warehouse Quantity</th>
							<th>Store Quantity</th>
							<th>Unit Cost</th>
						</tr>
					</thead>
					<tbody>
						<!-- TODO: Iterate through keys instead of manually creating them. -->
						{% for item in items %}
						<tr>
							<td>{{item.id}}</td>
							<td>{{item.itemCode}}</td>
							<td>{{item.supplierCode}}</td>
							<td>{{item.category}}</td>
							<td>{{item.itemType}}</td>
							<td>{{item.brand}}</td>
							<td>{{item.itemModel}}</td>
							<td>{{item.supplier.description}}</td>
							<td>{{item.minimumRequired}}</td>
							<td>{{item.warehouse_quantity}}</td>
							<td>{{item.store_quantity}}</td>
							<td>P {{item.unit_cost}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<a href="#" class="btn btn-info">Print</a>
				<a href="#" class="btn btn-success">Download CSV</a>
			</div>
		</div>
	</div>
{% endblock %}

inventory/templates/reports/sales_reports.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Sales Reports</h1>
				<p>This page will output all the items sold in a particular period. The data will be acquired from the Sales and Item Model. </p>
				<hr>
				<form class="form-inline">
					<div class="form-group">
						<label>Date Period: </label>
						<input type="date" class="form-control">
					</div>
					<select name="item_id">
						<option>Category | Brand | Model</option>
					</select>
					<div class="form-group">
						<input type="submit" class="btn btn-danger" value="Add">
					</div>
				</form>
			</div>
		</div><br>
		<div class="row">
			<div class="col-md-6">
				<table class="table table-striped table-bordered">
					<thead>
						<tr>
							<th colspan="2">Results Summary</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Date Period</td>
							<td>{{ date_period }}</td>
						</tr>
						<tr>
							<td>Total Items Sold</td>
							<td>{{ sales_length }}</td>
						</tr>
						<tr>
							<td>Total Sales</td>
							<td>{{ sales_total }}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		
		<div class="row">
			<div class="col-md-12">
				<table id="sales_reports" class="table table-bordered">
					<thead>
						<tr>
							<th colspan="9">Results (1)</th>
						</tr>
						<tr>
							<th>Date</th>
							<th>Category</th>
							<th>Type</th>
							<th>Brand</th>
							<th>Model</th>
							<th>Quantity</th>
							<th>Unit Cost</th>
							<th>Total Cost</th>
						</tr>
					</thead>
					<tbody>
						{% for sale in sales %}
						<tr>
							<td>{{sale.date}}</td>
							<td>{{sale.item.category}}</td>
							<td>{{sale.item.itemType}}</td>
							<td>{{sale.item.brand}}</td>
							<td>{{sale.item.itemModel}}</td>
							<td>{{sale.quantity}}</td>
							<td>{{sale.item.unit_cost}}</td>
							<td>{{sale.total_cost}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
		
		<div class="row">
			<div class="col-md-12">
				<a href="#" class="btn btn-info">Print</a>
				<a href="#" class="btn btn-success">Download CSV</a>
			</div>
		</div>
		
	</div>
	
{% endblock %}